blog/config/routes.rb
Rails.application.routes.draw do

  get 'auth/login'

  resources :posts
  root to: "blog#list"
  get "articles/:id" => "blog#article", as: "article"
  post "comments/:article_id/" => "blog#comments", as: "comment"

  get "auth/login" => "auth#login", as: "login"
  post "auth/verify" => "auth#verify", as: "verify_login"

end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  attr_accessor :happy

  validates :body, presence: true, length: { minimum: 20 }
  validates :name, presence: true, length: { minimum: 5}
end

blog/app/models/post.rb
class Post < ActiveRecord::Base

  validate :title, presence: true
  validate :body, presence: true
  validate :date_published, presence: true
  validate :published, presence: true

  has_many :comments

end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

blog/app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def login
  end

  def verify
    if params[:password] == "password"
      session[:admin] = true
      redirect_to posts_path
    else
      @message = "Sorry yo. THIS AREA RESTRICTED YO. NSA and FBI have been NOTIFIED.!!!!111!!"
      render :login
    end
  end
end

blog/app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def list
    @posts = Post.all.order("date_published desc")
  end

  def article
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def comments
    @post = Post.find(params[:article_id])
    @comment = @post.comments.build(comment_params)
    if @comment.save
      redirect_to article_path(@post)
    else
      render :article
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:body, :name, :happy)
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def authenticate!
      unless session[:admin] == true
        redirect_to login_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :title, :published, :date_published)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/auth_helper.rb
module AuthHelper
end

blog/app/helpers/blog_helper.rb
module BlogHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/blog/article.html.erb
<div class="post">
  <h2><%= @post.title %></h2>
  <p><%= @post.date_published %></p>
  <%= simple_format @post.body %>


  <div class="comments">
    <h5>Comments</h5>



    <ol>
      <% @post.comments.each do |comment| %>
        <li><%= comment.body %></li>
      <% end %>
    </ol>

    <% if @comment.errors.any? %>
      <%= @comment.errors.full_messages.join(", ") %>
    <% end %>
    <%= form_for @comment, url: comment_path(article_id: @post.id) do |f|%>
      <div>
        <%= f.text_area :body, rows: 5, cols:40 %>
      </div>
      <div>
        <%= f.label :name, "Your Name" %>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :happy %>
        <%= f.select :happy, %w(happy ok sad) %>
      </div>
      <%= f.submit "Add Your Ridiculous Comment" %>
    <% end %>

  </div>

</div>

blog/app/views/blog/list.html.erb
<% @posts.each do |post| %>
  <div class="post">
    <h2><%= link_to post.title, article_path(post) %></h2>
    <p><%= post.date_published %></p>
    <%= simple_format truncate(post.body, length: 300) %>
    <%= link_to "<-- Read More -->", article_path(post), class: "btn btn-large btn-success"%>
  </div>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to "BaconBlog.com", root_path %></h1>

<%= yield %>

</body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :date_published %><br>
    <%= f.date_select :date_published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Title</th>
      <th>Published</th>
      <th>Date published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.body %></td>
        <td><%= post.title %></td>
        <td><%= post.published %></td>
        <td><%= post.date_published %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<p>
  <strong>Date published:</strong>
  <%= @post.date_published %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>